const express = require("express");
const app = express();
const cors = require("cors");
const userRoutes = require("./Controllers/Routes/user");
app.use(cors());
app.use(express.json());
require("dotenv").config();
const port = 3000;
app.use("/user", userRoutes);
app.listen(port);
console.log("test");
